(define (sumOfLargestTwoSquared x y z)
  (define (square num) (* num num))
  (define (squareSum a b) (+ (square a) (square b)))
  (cond ((and (>= (+ x y) (+ y z)) (>= (+ x y) (+ x z))) (squareSum x y))
        ((and (>= (+ x z) (+ y z)) (>= (+ x y) (+ y z))) (squareSum x z))
        (else (squareSum y z))))